jobs:
- job: buildandtest
  pool:
    vmImage: ubuntu-latest
  steps:
    # Publish an artifact called "drop"
    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: '$(Build.ArtifactStagingDirectory)'
        artifactName: drop

    # Deploy to Azure Web App staging
    - task: AzureWebApp@1
      inputs:
        azureSubscription: 'ff8975f4-7184-430d-a97a-4bbcab893446'
        appType: webApp
        appName: 'azubuntuwebapp3_stage'
        deployToSlotOrASE: true
        resourceGroupName: DevopsDemo1
        slotName: 'staging'
        package: '$(Build.ArtifactStagingDirectory)/**/*.zip'

